name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: ghc {% raw %} ${{ matrix.ghc }} {% endraw %}
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        cabal: ["2.4"]
        ghc:
          - "8.8.4"

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: {% raw %} ${{ matrix.ghc }} {% endraw %}
        cabal-version: {% raw %} ${{ matrix.cabal }} {% endraw %}

    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: {% raw %} ${{ runner.os }}-${{ matrix.ghc }}-cabal {% endraw %}

    - name: Build
      run: |
        cabal v2-update
        cabal v2-build --enable-tests --enable-benchmarks

    - name: Test
      run: |
        cabal v2-test --enable-tests
