-- | This module define the type to process reports generated by the generator
module Capability.ReportPreProcessor (
  ReportPreProcessorM (..),
) where

import As
import Core.MyError
import Error

import Control.Monad.Catch (MonadThrow)
import Path

class (Monad m) => ReportPreProcessorM m where
  preProcessJavaCoreReport :: (WithError err m, As err MyError, MonadThrow m) => Path Rel File -> Path Rel Dir -> Path Abs File -> m (Path Abs File)
  preProcessHeapDumpReport :: (WithError err m, As err MyError, MonadThrow m) => Path Rel File -> Path Rel Dir -> Path Abs File -> m (Path Abs File)
  preProcessGCReport :: (WithError err m, As err MyError, MonadThrow m) => Path Rel File -> Path Rel Dir -> Path Abs File -> m (Path Abs File)
