questions:
  name:
    question: What's the name of the project?
    type: input
    default: test-prj1

  description:
    question: Project description?
    type: input
    default: Please refer to https://github.com/hughjfchen/test-prj1 for more info.

  nixos_release:
    question: Which nixos release?
    type: input
    default: "2105"

  ghc_version:
    question: Which GHC version?
    type: input
    default: "8.10.4"

  stackage_version:
    question: stackage version?
    type: input
    default: lts-18.5
