questions:
  name:
    question: What's the name of the project?
    type: input
    default: test4

  description:
    question: Project description?
    type: input
    default: Please refer to https://github.com/hughjfchen/test4 for more info.

  nixos_release:
    question: Which nixos release?
    type: input
    default: "21.11"

  ghc_version:
    question: Which GHC version?
    type: input
    default: "8.10.7"
