apiVersion: v1
kind: Service
metadata:
  name: {{name}}
  labels:
    run: {{name}}
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: {{name}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{name}}
spec:
  selector:
    matchLabels:
      run: {{name}}
  replicas: 1
  template:
    metadata:
      labels:
        run: {{name}}
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: {{name}}secret
      - name: configmap-volume
        configMap:
          name: {{name}}configmap
      containers:
      - name: {{name}}https
        image: hughjfchen/{{name}}:0.0.1.0
        resources:
          requests:
            memory: "1024Mi"
            cpu: "2000m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/{{name}}/ssl
          name: secret-volume
        - mountPath: /etc/{{name}}/conf.d
          name: configmap-volume
