cradle:
  cabal:
    - path: "./src"
      component: "lib:{{name}}"

    - path: "./app"
      component: "{{name}}:exe:{{name}}-exe"

    - path: "./test"
      component: "{{name}}:test:{{name}}-test"

    - path: "./benchmark"
      component: "{{name}}:bench:{{name}}-benchmark"
