questions:
  name:
    question: What's the name of the project?
    type: input
    default: test-prj1

  description:
    question: Project description?
    type: input
    default: Please refer to https://github.com/hughjfchen/test-prj1 for more info.

  nixos_release:
    question: Which nixos release?
    type: input
    default: "21.05"

  ghc_version:
    question: Which GHC version?
    type: input
    default: "8.10.7"

  index_state:
    question: index-state of hackage database?
    type: input
    default: 2021-09-13T00:00:00Z
