
-- This file is generated by the DataFiller free software.
-- This software comes without any warranty whatsoever.
-- Use at your own risk. Beware, this script may destroy your data!
-- License is GPLv3, see http://www.gnu.org/copyleft/gpl.html
-- Get latest version from http://www.coelho.net/datafiller.html

-- Data generated by: /usr/local/bin/datafiller
-- Version 2.0.1-dev (r832 on 2015-11-01)
-- For postgresql on 2017-05-03T12:34:39.879063 (UTC)
-- 
-- fill table data.user (2)
\echo # filling table data.user (3)
COPY :data_schema.user (id,name,email,"password") FROM STDIN (FREEZE ON);
1	test1	test1@test1.com	pass1111
2	test2	test2@test2.com	pass2222
3	test3	test3@test3.com	pass3333
\.

-- restart sequences
ALTER SEQUENCE :data_schema.user_id_seq RESTART WITH 4;
ALTER SEQUENCE :data_schema.jobs_id_seq RESTART WITH 1;
-- 
-- analyze modified tables
ANALYZE :data_schema.user;
ANALYZE :data_schema.jobs;
